micronaut:
  application:
    name: freteRest
<<<<<<< HEAD
grpc:
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    fretes:
      address: "localhost:50051"
      plaintext: true
      max-retry-attemps: 10
=======
>>>>>>> origin/main
